server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/db_jxc_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false